docs/bioregistry/celltypist.ipynb, docs/datatype/10-scrna.ipynb, docs/datatype/40-multimodal.ipynb
Need to merge lamindb to main to get this to pass!
=> 🚚 Move `add_labels` from `FeatureManager` to `Data`

docs/datatype/10-scrna.ipynb, docs/datatype/20-scrna-1.ipynb, docs/datatype/30-flow.ipynb, docs/datatype/40-multimodal.ipynb, docs/datatype/60-bulkrna.ipynb
TODO:
- in the flow guide, empty string cell markers should be ignored but not subsetted.
=> ♻️ Polish data type guides

docs/scrna.ipynb
Needs https://github.com/laminlabs/lamindb/pull/1063
=> 📝 Enable default_field for inspect and validate

docs/birds-eye.ipynb, docs/celltypist.ipynb
TBD whether displaying the matrixplot works like this due to the pathing and what jupyter actually sees. Have to run now.
Fixes #37
=> Address LH birds eye review

docs/flow.ipynb
=> Address flow cytomery review

docs/scrna.ipynb, docs/scrna2.ipynb
=> Integrate scRNA-seq review

docs/bulkrna.ipynb, docs/by-datatype.md, docs/facs.ipynb, docs/multimodal.ipynb, docs/scrna.ipynb, docs/scrna2.ipynb
- Use ensembl_gene_id for both scrna datasets
=> 📝 Rename flow to facs, removed modality assignment

docs/scrna2.ipynb, docs/scrna5.ipynb, noxfile.py
=> 📝 Use scvi in the scrna notebook

docs/scrna5.ipynb
=> 📝 Show an example of ln.Dataset.indexed usage

docs/scrna5.ipynb
=> 📝 Show virtual inner join in mapped

docs/scrna.ipynb, docs/scrna2.ipynb, docs/scrna3.ipynb, docs/scrna4.ipynb, docs/scrna5.ipynb
https://lamin.ai/laminlabs/lamindata/records/core/Transform
=> ♻️ Iterate scrna guide

docs/bulkrna.ipynb, docs/celltypist.ipynb, docs/facs.ipynb, docs/facs4.ipynb, docs/scrna.ipynb, docs/scrna2.ipynb, docs/scrna4.ipynb, docs/scrna5.ipynb
- https://github.com/laminlabs/lamindb/pull/1390
=> 📝 Show virtual outer join in mapped

docs/analysis-registries.ipynb, docs/bulkrna.ipynb, docs/facs.ipynb, docs/facs2.ipynb, docs/spatial.ipynb
Similar fixes:
- https://github.com/laminlabs/lamin-spatial/commit/07a736c1a32f0c1b2e43768cfb72b0d5cb610b80
- https://github.com/laminlabs/cellxgene-lamin/commit/87aaff795b8a790fe7434e5453909e97f2b522ce
=> ♻️ Replace `.features.add_from_anndata()` with `.features._add_set_from_anndata()`

docs/scrna6.ipynb, noxfile.py
=> 📝 Add tiledbsoma scrna guide

docs/scrna6.ipynb, noxfile.py
=> 📝 Use Artifact.backed to connect to tiledbsoma

docs/analysis-flow.ipynb, docs/project-flow.ipynb, docs/scrna3.ipynb, docs/scrna6.ipynb
=> 📝 Rename Artifact.backed to Artifact.open

docs/public-ontologies.md
Fixes #99 
- Also comments out Drug because we're not showing it here
- Adds chebi to drug but w/e
=> 📝 Link access pages

docs/analysis-flow-scripts/register_example_file.py, docs/analysis-flow.ipynb, docs/facs.ipynb, docs/facs2.ipynb, docs/multimodal.ipynb, docs/perturbation.ipynb, docs/scrna.ipynb, docs/scrna2.ipynb, docs/spatial.ipynb
Propagates:
- https://github.com/laminlabs/lamindb/pull/2081
=> 🔥 Remove `Curator.add_validated_from()`

.github/workflows/build.yml, docs/sc-imaging.ipynb, docs/sc-imaging2.ipynb
Fixes https://github.com/laminlabs/lamin-usecases/issues/195
=> 🎨 Run all on dispatch & fix CI

docs/sc-imaging2.ipynb
Removes the forward slash fix, the notebook runs through normally without.
=> ⏪  Remove anndata forward slash fix
